### ISSUE TITLE
 mideu extract giving error

### ISSUE THREAD

**Issue by jnbharat1992** [adelosa/mciutil#17] opened 2016-03-08 14:34 UTC
OS Ubuntu 14.04LTS
TT068T0.2015-10-16-10-42-18.001 is data file  MasterCard IPM 
converted the above file to EBCDIC ,assuming my file is Ascii 
mideu extract TT068T0.2015-10-16-10-42-18.001.out 

"Traceback (most recent call last):
  File "/usr/local/bin/mideu", line 9, in <module>
    load_entry_point('mciutil==0.4.1', 'console_scripts', 'mideu')()
  File "/usr/local/lib/python2.7/dist-packages/mciutil-0.4.1-py2.7.egg/mciutil/cli/mideu.py", line 26, in cli_entry
    _main(args)
  File "/usr/local/lib/python2.7/dist-packages/mciutil-0.4.1-py2.7.egg/mciutil/cli/mideu.py", line 48, in _main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/mciutil-0.4.1-py2.7.egg/mciutil/cli/extract.py", line 52, in extract_command
    ) for record in input_file
  File "/usr/local/lib/python2.7/dist-packages/mciutil-0.4.1-py2.7.egg/mciutil/mciutil.py", line 275, in get_message_elements
    bit_config[bit],
KeyError: 8"

**Comment by adelosa** [comment] 2016-03-08 21:30
This error indicates missing config for bit 8 in the IPM message. The config file is mideu.yml. You can create your own config file and place in current directory or your home directory. Just add entry for bit 8.
I'll include definition for bit 8 in next update. Depending on the message type you may find other missing bits after this one.

**Comment by jnbharat1992** [comment] 2016-03-09 06:20
Hi Anthony

my file is TT068T0 format
Could you help me how to convert to csv.

**Comment by adelosa** [comment] 2016-03-12 23:58
You must have an issue with your file. There is no bit 8 in the MasterCard IPM format. Confirm that the message bitmap aligns to a valid MasterCard IPM record type... Also check that the file is in the 1014 blocked format as bitmap errors like this can be caused by the file not being blocked correctly.. See https://mciutil.readthedocs.org/en/latest/usage.html#blocked-file-format

If you are working with non MasterCard files that are formatted in ISO8583 format then you can copy https://github.com/adelosa/mciutil/blob/develop/mciutil/cli/mideu.yml, place in your home directory and update the bit definitions to suit your requirements.

**Comment by adelosa** [comment] 2016-03-13 10:21
I've just released v0.4.2 onto pypi.. This has a complete DE mapping for MasterCard IPM files. If it doesn't work now, please let me know.

**Comment by adelosa** [comment] 2016-08-02 12:11
Assuming you worked out what was wrong.. closing.

**Closed by adelosa** 2016-08-02 12:11 UTC
